# Generated by Django 2.2.16 on 2022-01-11 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mx_multilingual_discovery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='multilingualdiscovery',
            options={'verbose_name': 'MultiLingualDiscovery'},
        ),
        migrations.AlterModelOptions(
            name='multilingualdiscoverytranslation',
            options={'verbose_name': 'MultiLingualDiscovery translation'},
        ),
        migrations.AlterField(
            model_name='multilingualdiscoverytranslation',
            name='master',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='mx_multilingual_discovery.MultiLingualDiscovery'),
        ),
    ]
