# Generated by Django 2.2.16 on 2022-05-02 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mx_multilingual_discovery', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='multilingualdiscovery',
            old_name='course_key',
            new_name='course_title',
        ),
    ]
