# Generated by Django 2.2.16 on 2022-01-11 09:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mx_multilingual_discovery', '0002_auto_20220111_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multilingualdiscoverytranslation',
            name='full_descriprion',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='Full Description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='multilingualdiscoverytranslation',
            name='short_descriprion',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='Short Description'),
            preserve_default=False,
        ),
    ]
