# Generated by Django 2.2.16 on 2022-05-02 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mx_multilingual_discovery', '0002_auto_20220502_0530'),
    ]

    operations = [
        migrations.RenameField(
            model_name='multilingualdiscovery',
            old_name='program_key',
            new_name='program_title',
        ),
    ]
