# Generated by Django 2.2.16 on 2022-01-11 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mx_multilingual_discovery', '0003_auto_20220111_0932'),
    ]

    operations = [
        migrations.RenameField(
            model_name='multilingualdiscoverytranslation',
            old_name='full_descriprion',
            new_name='full_description',
        ),
        migrations.RenameField(
            model_name='multilingualdiscoverytranslation',
            old_name='short_descriprion',
            new_name='short_description',
        ),
    ]
