# Generated by Django 2.2.16 on 2022-01-11 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mx_multilingual_discovery', '0004_auto_20220111_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multilingualdiscoverytranslation',
            name='full_description',
            field=models.TextField(blank=True, null=True, verbose_name='Full Description'),
        ),
        migrations.AlterField(
            model_name='multilingualdiscoverytranslation',
            name='short_description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Short Description'),
        ),
    ]
