# Generated by Django 2.2.16 on 2021-05-11 08:52

import course_discovery.apps.course_metadata.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('get_full_image_url', models.ImageField(blank=True, null=True, upload_to=course_discovery.apps.course_metadata.utils.UploadToFieldNamePath(path='media/subject/new_image_url/', populate_from='id'), validators=[django.core.validators.FileExtensionValidator(['png'])])),
            ],
        ),
    ]
