# Generated by Django 2.2.16 on 2021-05-11 06:00

import course_discovery.apps.course_metadata.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0251_add_honor_course_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='new_image_url',
            field=models.ImageField(blank=True, null=True, upload_to=course_discovery.apps.course_metadata.utils.UploadToFieldNamePath(path='media/subject/new_image_url/', populate_from='uuid'), validators=[django.core.validators.FileExtensionValidator(['png'])]),
        ),
        migrations.AlterField(
            model_name='leveltypetranslation',
            name='name_t',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
    ]
