# Generated by Django 2.2.16 on 2021-05-11 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0252_auto_20210511_0600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='new_image_url',
        ),
    ]
