# Generated by Django 2.2.16 on 2022-04-27 12:31

from django.db import migrations
import sortedm2m.fields
import taggit_autosuggest.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('course_metadata', '0253_remove_subject_new_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='program_subjects',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, to='course_metadata.Subject'),
        ),
        migrations.AddField(
            model_name='program',
            name='program_topics',
            field=taggit_autosuggest.managers.TaggableManager(blank=True, help_text='Pick a tag from the suggestions. To make a new tag, add a comma after the tag name.', related_name='program_topics', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
